export type Species = {
  id: string;
  name: string;
  latinName?: string;
  category: string;
  biome: string;
  region: string;
  status: string;
  signs: string[];
  behavior: string;
  importance: string;
};

export const speciesData: Species[] = [
  {
    id: 'white-tailed-deer',
    name: 'White-tailed Deer',
    latinName: 'Odocoileus virginianus',
    category: 'Mammal',
    biome: 'Forest',
    region: 'North America',
    status: 'Common',
    signs: ['Heart-shaped tracks', 'Browsing on saplings', 'Oval pellets', 'Rubbed bark'],
    behavior: 'Crepuscular herbivore active at dawn and dusk. Forms small herds in winter. Bucks shed antlers in late winter.',
    importance: 'Keystone browser controlling understory growth. Important prey base for large predators. Overpopulation can damage forest regeneration.',
  },
  {
    id: 'red-fox',
    name: 'Red Fox',
    latinName: 'Vulpes vulpes',
    category: 'Mammal',
    biome: 'Forest',
    region: 'North America, Europe',
    status: 'Common',
    signs: ['Dog-like tracks in line', 'Musky scent', 'Cached prey', 'Den entrances'],
    behavior: 'Solitary omnivore hunting small mammals and birds. Highly adaptable to human presence. Uses multiple dens.',
    importance: 'Controls rodent populations. Indicator of healthy small prey communities. Adapts well to edge habitats.',
  },
  {
    id: 'black-bear',
    name: 'Black Bear',
    latinName: 'Ursus americanus',
    category: 'Mammal',
    biome: 'Forest',
    region: 'North America',
    status: 'Common',
    signs: ['Large 5-toed tracks', 'Claw marks on trees', 'Scat with berries', 'Overturned logs'],
    behavior: 'Omnivorous solitary animal. Excellent climber. Hibernates in winter. Highly intelligent with strong memory.',
    importance: 'Top omnivore dispersing seeds across vast ranges. Den sites indicate old-growth forest. Sensitive to human disturbance.',
  },
  {
    id: 'pileated-woodpecker',
    name: 'Pileated Woodpecker',
    latinName: 'Dryocopus pileatus',
    category: 'Bird',
    biome: 'Forest',
    region: 'North America',
    status: 'Common',
    signs: ['Large rectangular excavations', 'Loud drumming', 'Wood chips at tree base', 'Distinctive call'],
    behavior: 'Excavates deep cavities in dead trees for insects. Monogamous pairs hold large territories. Loud and conspicuous.',
    importance: 'Creates nesting cavities used by dozens of other species. Indicates mature forest with standing dead wood.',
  },
  {
    id: 'barred-owl',
    name: 'Barred Owl',
    latinName: 'Strix varia',
    category: 'Bird',
    biome: 'Forest',
    region: 'North America',
    status: 'Common',
    signs: ['Who-cooks-for-you call', 'Pellets with bones', 'White wash on trees', 'Silent flight'],
    behavior: 'Nocturnal hunter of small mammals and birds. Nests in tree cavities. Highly vocal especially in breeding season.',
    importance: 'Top predator controlling rodent populations. Cavity nester requiring mature forest structure.',
  },
  {
    id: 'wood-frog',
    name: 'Wood Frog',
    latinName: 'Lithobates sylvaticus',
    category: 'Amphibian',
    biome: 'Forest',
    region: 'North America',
    status: 'Common',
    signs: ['Duck-like quacking calls', 'Egg masses in vernal pools', 'Hopping through leaf litter'],
    behavior: 'Freeze-tolerant amphibian surviving solid freezing in winter. Explosive breeder in early spring vernal pools.',
    importance: 'Indicator of healthy seasonal wetlands. Critical prey for many forest animals. Highly sensitive to pollution.',
  },
  {
    id: 'red-backed-salamander',
    name: 'Red-backed Salamander',
    latinName: 'Plethodon cinereus',
    category: 'Amphibian',
    biome: 'Forest',
    region: 'Eastern North America',
    status: 'Common',
    signs: ['Under logs and bark', 'Moist microhabitats', 'No aquatic stage'],
    behavior: 'Lungless salamander breathing through skin. Territorial, defending small home ranges. Entirely terrestrial life cycle.',
    importance: 'Most abundant vertebrate in many forests by biomass. Critical nutrient cycler consuming invertebrates.',
  },
  {
    id: 'bison',
    name: 'American Bison',
    latinName: 'Bison bison',
    category: 'Mammal',
    biome: 'Grassland',
    region: 'North America',
    status: 'Vulnerable',
    signs: ['Large cloven hoofprints', 'Wallows', 'Grazed patches', 'Scat piles'],
    behavior: 'Large grazing herbivore living in herds. Creates diverse habitat patches through grazing and wallowing.',
    importance: 'Keystone grazer shaping grassland structure. Historically numbered in millions, now recovering from near extinction.',
  },
  {
    id: 'prairie-dog',
    name: 'Black-tailed Prairie Dog',
    latinName: 'Cynomys ludovicianus',
    category: 'Mammal',
    biome: 'Grassland',
    region: 'North America',
    status: 'Near Threatened',
    signs: ['Colonial burrow systems', 'Barking calls', 'Mounded entrances', 'Clipped vegetation'],
    behavior: 'Social burrowing rodent living in large colonies. Complex communication system with predator-specific alarm calls.',
    importance: 'Ecosystem engineer creating habitat for over 100 species. Burrows aerate soil and capture water.',
  },
  {
    id: 'burrowing-owl',
    name: 'Burrowing Owl',
    latinName: 'Athene cunicularia',
    category: 'Bird',
    biome: 'Grassland',
    region: 'Americas',
    status: 'Vulnerable',
    signs: ['Ground burrows', 'Long legs', 'White eyebrows', 'Daytime activity'],
    behavior: 'Diurnal owl nesting in prairie dog burrows. Often seen standing at burrow entrance. Feeds on insects and small mammals.',
    importance: 'Dependent on burrowing mammals for nesting sites. Indicator of intact prairie dog colonies.',
  },
  {
    id: 'meadowlark',
    name: 'Western Meadowlark',
    latinName: 'Sturnella neglecta',
    category: 'Bird',
    biome: 'Grassland',
    region: 'North America',
    status: 'Common',
    signs: ['Flute-like song', 'Yellow breast with V', 'Ground nests', 'Perches on fences'],
    behavior: 'Ground-nesting songbird with distinctive melodious call. Feeds on insects and seeds in open grasslands.',
    importance: 'Sensitive to habitat fragmentation. Declining population indicates grassland degradation.',
  },
  {
    id: 'great-blue-heron',
    name: 'Great Blue Heron',
    latinName: 'Ardea herodias',
    category: 'Bird',
    biome: 'Wetland',
    region: 'North and Central America',
    status: 'Common',
    signs: ['Large wading tracks', 'Fish spearing', 'Stick nests in colonies', 'Slow stalking'],
    behavior: 'Patient wading bird hunting fish, frogs, and small mammals. Nests colonially in tall trees near water.',
    importance: 'Indicator of healthy fish populations. Sensitive to water pollution and habitat loss.',
  },
  {
    id: 'beaver',
    name: 'North American Beaver',
    latinName: 'Castor canadensis',
    category: 'Mammal',
    biome: 'Wetland',
    region: 'North America',
    status: 'Common',
    signs: ['Dams and lodges', 'Gnawed stumps', 'Scent mounds', 'Tail slap alarm'],
    behavior: 'Ecosystem engineer building dams to create ponds. Monogamous family groups. Primarily nocturnal.',
    importance: 'Creates wetland habitat for hundreds of species. Stores water and reduces erosion. Nature\'s hydrologist.',
  },
  {
    id: 'wood-duck',
    name: 'Wood Duck',
    latinName: 'Aix sponsa',
    category: 'Bird',
    biome: 'Wetland',
    region: 'North America',
    status: 'Common',
    signs: ['Colorful male plumage', 'Tree cavity nests', 'Squealing call', 'Feeds on water surface'],
    behavior: 'Cavity-nesting duck requiring wooded wetlands. Ducklings leap from nest cavities within day of hatching.',
    importance: 'Recovered from near extinction due to conservation efforts. Indicator of quality wetland forest.',
  },
  {
    id: 'painted-turtle',
    name: 'Painted Turtle',
    latinName: 'Chrysemys picta',
    category: 'Reptile',
    biome: 'Wetland',
    region: 'North America',
    status: 'Common',
    signs: ['Basking on logs', 'Red markings on shell', 'Nest holes in sandy banks'],
    behavior: 'Basking turtle requiring clean water and sunny logs. Omnivorous diet. Freeze-tolerant hatchlings.',
    importance: 'Indicator of water quality. Important scavenger and algae grazer maintaining ecosystem balance.',
  },
  {
    id: 'sea-otter',
    name: 'Sea Otter',
    latinName: 'Enhydra lutris',
    category: 'Mammal',
    biome: 'Coast',
    region: 'North Pacific',
    status: 'Endangered',
    signs: ['Floating on back', 'Tool use with rocks', 'Kelp wrapping', 'Rafting groups'],
    behavior: 'Marine mammal using tools to crack open shellfish. Wraps in kelp while sleeping. Maintains kelp forests by eating urchins.',
    importance: 'Keystone species preventing urchin barrens. Essential for kelp forest health. Fur trade nearly caused extinction.',
  },
  {
    id: 'brown-pelican',
    name: 'Brown Pelican',
    latinName: 'Pelecanus occidentalis',
    category: 'Bird',
    biome: 'Coast',
    region: 'Americas - coastal',
    status: 'Common',
    signs: ['Plunge diving', 'Large throat pouch', 'Colonial nesting', 'Gliding in lines'],
    behavior: 'Dramatic plunge diver from heights to catch fish. Nests on coastal islands. Flies in formation low over waves.',
    importance: 'Recovered from DDT-related decline. Indicator of coastal fish populations and water quality.',
  },
  {
    id: 'hermit-crab',
    name: 'Hermit Crab',
    latinName: 'Paguroidea',
    category: 'Invertebrate',
    biome: 'Coast',
    region: 'Worldwide coastal',
    status: 'Common',
    signs: ['Snail shell with legs', 'Tide pool resident', 'Scavenging behavior'],
    behavior: 'Shell-dwelling scavenger essential to tide pool cleanup. Switches shells as it grows. Social interactions at shell swaps.',
    importance: 'Recycles dead organic matter. Indicator of healthy shell availability and tide pool ecosystems.',
  },
  {
    id: 'mountain-goat',
    name: 'Mountain Goat',
    latinName: 'Oreamnos americanus',
    category: 'Mammal',
    biome: 'Mountains',
    region: 'North America',
    status: 'Common',
    signs: ['Cloven tracks on cliffs', 'White coat', 'Salt lick sites', 'Bedding sites on ledges'],
    behavior: 'Extreme terrain specialist with non-slip hooves. Feeds on alpine vegetation. Highly sure-footed on vertical faces.',
    importance: 'Indicator of intact alpine ecosystems. Sensitive to climate change affecting high elevation habitats.',
  },
  {
    id: 'golden-eagle',
    name: 'Golden Eagle',
    latinName: 'Aquila chrysaetos',
    category: 'Bird',
    biome: 'Mountains',
    region: 'Northern Hemisphere',
    status: 'Common',
    signs: ['Large stick nests on cliffs', 'Soaring on thermals', 'Golden nape', 'Talons and prey remains'],
    behavior: 'Powerful raptor hunting mammals and birds. Monogamous pairs maintain large territories. Uses multiple nest sites.',
    importance: 'Top predator indicator of healthy prey populations. Requires vast undisturbed ranges.',
  },
  {
    id: 'pika',
    name: 'American Pika',
    latinName: 'Ochotona princeps',
    category: 'Mammal',
    biome: 'Mountains',
    region: 'Western North America',
    status: 'Vulnerable',
    signs: ['Hay piles', 'Eek calls', 'Talus habitat', 'Round ears'],
    behavior: 'Cold-adapted mammal storing vegetation for winter. Does not hibernate. Highly vocal. Cannot tolerate heat.',
    importance: 'Climate change indicator species. Populations retreating upslope. Sentinel for alpine ecosystem health.',
  },
  {
    id: 'desert-tortoise',
    name: 'Desert Tortoise',
    latinName: 'Gopherus agassizii',
    category: 'Reptile',
    biome: 'Desert',
    region: 'Southwestern North America',
    status: 'Vulnerable',
    signs: ['Deep burrows', 'Domed shell tracks', 'Scat with plant fiber', 'Cactus feeding'],
    behavior: 'Long-lived herbivore spending 95% of life underground. Emerges after rains to feed and breed. Stores water in bladder.',
    importance: 'Burrows provide shelter for 350+ species. Long lifespan makes populations slow to recover from threats.',
  },
  {
    id: 'roadrunner',
    name: 'Greater Roadrunner',
    latinName: 'Geococcyx californianus',
    category: 'Bird',
    biome: 'Desert',
    region: 'Southwestern North America',
    status: 'Common',
    signs: ['X-shaped tracks', 'Running gait', 'Lizard hunting', 'Cuckoo calls'],
    behavior: 'Ground-dwelling cuckoo running up to 20 mph. Hunts lizards, snakes, insects. Able to kill rattlesnakes.',
    importance: 'Controls reptile and rodent populations. Adapted to extreme heat through specialized physiology.',
  },
  {
    id: 'coyote',
    name: 'Coyote',
    latinName: 'Canis latrans',
    category: 'Mammal',
    biome: 'Urban Edge',
    region: 'North America',
    status: 'Common',
    signs: ['Dog-like tracks', 'Howling chorus', 'Scat with fur', 'Dens under structures'],
    behavior: 'Highly adaptable omnivore thriving near humans. Hunts alone or in pairs. Mostly nocturnal in urban areas.',
    importance: 'Most successful large predator in human landscapes. Controls rodent populations. Adaptability demonstrates resilience.',
  },
  {
    id: 'peregrine-falcon',
    name: 'Peregrine Falcon',
    latinName: 'Falco peregrinus',
    category: 'Bird',
    biome: 'Urban Edge',
    region: 'Worldwide',
    status: 'Common',
    signs: ['Ledge nests', 'Prey plucking sites', 'Dive bombing', 'Sharp kak-kak calls'],
    behavior: 'Fastest animal on earth diving at 240 mph to strike birds. Adapted to nest on buildings and bridges in cities.',
    importance: 'DDT recovery success story. Urban populations thrive on abundant pigeons. Indicator of aerial prey health.',
  },
  {
    id: 'opossum',
    name: 'Virginia Opossum',
    latinName: 'Didelphis virginiana',
    category: 'Mammal',
    biome: 'Urban Edge',
    region: 'North America',
    status: 'Common',
    signs: ['Hand-like tracks', 'Opposable thumbs', 'Playing dead', 'Nocturnal foraging'],
    behavior: 'Only North American marsupial. Opportunistic omnivore. Famous for playing dead when threatened. Tick consumer.',
    importance: 'Eats thousands of ticks reducing Lyme disease. Resistant to rabies. Important urban scavenger.',
  },
];

export const biomeTypes = ['Forest', 'Grassland', 'Wetland', 'Coast', 'Mountains', 'Desert', 'Urban Edge'];
export const categoryTypes = ['Mammal', 'Bird', 'Reptile', 'Amphibian', 'Invertebrate'];
